using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Macro01
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void GoButton_Click(object sender, EventArgs e)
        {
            int timeout = 60;
            iMacros.App oApp = new iMacros.App();
            // C# snippet generated by iMacros Editor.
            // See http://wiki.imacros.net/Web_Scripting for details on how to use the iMacros Scripting Interface.

            iMacros.AppClass iim = new iMacros.AppClass();
            // iMacros.Status status = iim.iimOpen("", true, timeout);
            iMacros.Status status;
            StringBuilder macro = new StringBuilder();
            macro.AppendLine(@"VERSION BUILD=7401110 RECORDER=FX");
            macro.AppendLine(@"SET !TIMEOUT 180");
            macro.AppendLine(@"SET !ENCRYPTION NO");
            macro.AppendLine(@"SET !EXTRACT_TEST_POPUP NO");
            macro.AppendLine(@"TAB T=1");
            //macro.AppendLine(@"URL GOTO=https://qatelau40/CAT/Login.aspx?gru=000000000");
            macro.AppendLine(@"URL GOTO=https://" + ServerName.Text + @"/CAT/Login.aspx?gru=000000000");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:Login1_UserName CONTENT=admin");
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:Login1_UserName CONTENT=" + UserName.Text);
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:form1 ATTR=ID:Login1_Password CONTENT=admin");
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:form1 ATTR=ID:Login1_Password CONTENT=" + Password.Text);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:form1 ATTR=ID:Login1_Login");
            macro.AppendLine(@"TAG POS=1 TYPE=SPAN ATTR=ID:MainNavigation1_lblClientName");
            macro.AppendLine(@"TAG POS=1 TYPE=TD ATTR=TXT:Telstra");
            macro.AppendLine(@"TAG POS=1 TYPE=TD ATTR=CLASS:homeleftcolumn");
            macro.AppendLine(@"TAG POS=1 TYPE=SPAN ATTR=TXT:Find<SP>Account");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:AccountSearch1_SearchBox CONTENT=1525853400");
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:AccountSearch1_SearchBox CONTENT=" + AccountNumber.Text);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:RADIO FORM=ID:form1 ATTR=ID:AccountSearch1_rblSearchType_1");
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:form1 ATTR=ID:AccountSearch1_SearchButton");
            macro.AppendLine(@"'TAG POS=1 TYPE=TD ATTR=TXT:CSR<SP>Login");
            macro.AppendLine(@"TAG POS=1 TYPE=A ATTR=ID:FindAccountGridView_ctl02_linkCSRLogin");
            macro.AppendLine(@"FRAME F=2");
            macro.AppendLine(@"'TAG POS=1 TYPE=IMG ATTR=SRC:*cv/scripts/images/eng/telstra*/b_logout_off.gif");
            string macroCode = macro.ToString();

            //status = iim.iimOpen("-V7", true, timeout);
            status = iim.iimOpen("-FX", true, timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimDisplay("Interface version =\n" + iim.iimGetInterfaceVersion().ToString(), timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimPlayCode(macroCode, timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimClose(timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            

        }

        private void runLogin(string serverName, string userName, string password, string accountNumber)
        {
            int timeout = 60;
            iMacros.App oApp = new iMacros.App();
            // C# snippet generated by iMacros Editor.
            // See http://wiki.imacros.net/Web_Scripting for details on how to use the iMacros Scripting Interface.

            iMacros.AppClass iim = new iMacros.AppClass();
            // iMacros.Status status = iim.iimOpen("", true, timeout);
            iMacros.Status status;
            StringBuilder macro = new StringBuilder();
            macro.AppendLine(@"VERSION BUILD=7401110 RECORDER=FX");
            macro.AppendLine(@"SET !TIMEOUT 180");
            macro.AppendLine(@"SET !ENCRYPTION NO");
            macro.AppendLine(@"SET !EXTRACT_TEST_POPUP NO");
            macro.AppendLine(@"TAB T=1");
            //macro.AppendLine(@"URL GOTO=https://qatelau40/CAT/Login.aspx?gru=000000000");
            //macro.AppendLine(@"URL GOTO=https://" + ServerName.Text + @"/CAT/Login.aspx?gru=000000000");
            macro.AppendLine(@"URL GOTO=https://" + serverName + @"/CAT/Login.aspx?gru=000000000");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:Login1_UserName CONTENT=admin");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:Login1_UserName CONTENT=" + UserName.Text);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:Login1_UserName CONTENT=" + userName);
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:form1 ATTR=ID:Login1_Password CONTENT=admin");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:form1 ATTR=ID:Login1_Password CONTENT=" + Password.Text);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:form1 ATTR=ID:Login1_Password CONTENT=" + password);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:form1 ATTR=ID:Login1_Login");
            macro.AppendLine(@"TAG POS=1 TYPE=SPAN ATTR=ID:MainNavigation1_lblClientName");
            macro.AppendLine(@"TAG POS=1 TYPE=TD ATTR=TXT:Telstra");
            macro.AppendLine(@"TAG POS=1 TYPE=TD ATTR=CLASS:homeleftcolumn");
            macro.AppendLine(@"TAG POS=1 TYPE=SPAN ATTR=TXT:Find<SP>Account");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:AccountSearch1_SearchBox CONTENT=1525853400");
            //macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:AccountSearch1_SearchBox CONTENT=" + AccountNumber.Text);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:form1 ATTR=ID:AccountSearch1_SearchBox CONTENT=" + accountNumber);
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:RADIO FORM=ID:form1 ATTR=ID:AccountSearch1_rblSearchType_1");
            macro.AppendLine(@"TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:form1 ATTR=ID:AccountSearch1_SearchButton");
            macro.AppendLine(@"'TAG POS=1 TYPE=TD ATTR=TXT:CSR<SP>Login");
            macro.AppendLine(@"TAG POS=1 TYPE=A ATTR=ID:FindAccountGridView_ctl02_linkCSRLogin");
            macro.AppendLine(@"FRAME F=2");
            macro.AppendLine(@"'TAG POS=1 TYPE=IMG ATTR=SRC:*cv/scripts/images/eng/telstra*/b_logout_off.gif");
            string macroCode = macro.ToString();

            //status = iim.iimOpen("-V7", true, timeout);
            status = iim.iimOpen("-FX", true, timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimDisplay("Interface version =\n" + iim.iimGetInterfaceVersion().ToString(), timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimPlayCode(macroCode, timeout);
            OutputBox.Text += status.ToString() + "\r\n";
            status = iim.iimClose(timeout);
            OutputBox.Text += status.ToString() + "\r\n";
        }
    }
}
